var gulp = require('gulp');
var react = require('gulp-react');
var plugins = require('gulp-load-plugins')();

gulp.task('jsx', function (){
return gulp.src('src/js/**/*.js')
    //.pipe(plugins.cached('jsx'))
    .pipe(plugins.react())
    .on('error', plugins.util.log)
    .pipe(gulp.dest('build/js/'));
});

gulp.task('sass', function() {
  return gulp.src('src/scss/main.scss')
    .pipe(plugins.sourcemaps.init())
    .pipe(plugins.sass())
    .pipe(plugins.sourcemaps.write({includeContent: false}))
    .pipe(plugins.sourcemaps.init({loadMaps: true})) // Load sourcemaps generated by sass
    //.pipe(plugins.autoprefixer({
    //  browsers: ['last 2 versions']
    //}))8
    .on('error', plugins.util.log)
    .pipe(plugins.sourcemaps.write('.'))
    .pipe(gulp.dest('./build/css'))
    .on('error', plugins.util.log);
});


gulp.task('serve', ['jsx', 'sass'], function (){
  gulp.watch('src/**/*.js', function (){
    gulp.start('jsx');
  });

  gulp.watch('src/scss/*.scss', function (){
    gulp.start('sass');  
  });
});

gulp.task('default',['serve']);
